### ISSUE TITLE
An error occurred in installing diesel_cli occur

### ISSUE THREAD

**Issue by RocooHash** [sgrif/diesel.rs-website#126]
when I run `cargo install diesel_cli`

toolchain = stable-x86_64-pc-windows-gnu
gcc-v = `gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)`

note that when **compile diesel_cli**
`note: D:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lsqlite3
          D:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lpq
          D:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmysql
          collect2.exe: error: ld returned 1 exit status`

**Comment by weiznich** [comment]
You miss a required dependency.

> If you run into an error like:
>```
>note: ld: library not found for -lmysqlclient >clang: error: linker command failed with exit >code 1 (use -v to see invocation) 
```
>This means you are missing the client library >needed for a database backend – mysqlclient >in this case. You can resolve this issue by >either installing the library (using the usual >way to do this depending on your operating >system) or by excluding the undesired default >library with the --no-default-features flag.
>
>For example, if you only have PostgreSQL installed, you can use this to install diesel_cli with only PostgreSQL:
>```
>cargo install diesel_cli --no-default-features --features postgres
>```


See the getting started guide for details.
