### ISSUE TITLE
Issue running Get Started example with PostGres

### ISSUE THREAD

**Issue by fabracht** [sgrif/diesel.rs-website#136]
How up to date is the documentation in this page http://diesel.rs/guides/getting-started.html?
I can't seem to make it work. Once I try to compile I get these:
[
![image](https://user-images.githubusercontent.com/22660453/133172902-f89f3afc-5f90-4cd2-8412-f18ff5849c99.png)
](url)
The first one "cannot find derive macro 'Queryable' in this scope is quite confusing because it comes from the file that was generated by diesel setup.

**Comment by weiznich** [comment]
The guides are up to date + there is a CI that checks that the linked examples compile. You likely miss a import in your crate root. That written this is not the place to ask such questions. Please use diesels discussion forum or the gitter channel for such questions.
