### ISSUE TITLE
fix: disable site in `http` and do 301 by redirecting it to `https`

### ISSUE THREAD

**Issue by vinayakkulkarni** [sgrif/diesel.rs-website#138]
As the title says, this is not a bug or anything, just as suggestion that stop serving the site via `http` & only use `https` for the users to be able to access it.

Thanks.

**Comment by weiznich** [comment]
Duplicate of #78

**Comment by vinayakkulkarni** [comment]
Sorry about this. My bad. Should've searched the issues first.
