### ISSUE TITLE
Improve website by telling what the project is about

### ISSUE THREAD

**Issue by iio7** [sgrif/diesel.rs-website#173]
I just saw a link for the Diesel website on lobste.rs, followed the link to the website, yet there is absolutely no information on the frontpage about what Diesel is, neither an about page, so I am left guessing looking at features.

I highly recommend that the first thing a persons sees, when visiting your website, is a clear cut message describing what Diesel is.

Just as an inspiration, take a look at https://www.postgresql.org/ or https://www.sqlite.org/ or https://www.openbsd.org/.

**Comment by weiznich** [comment]
I'm closing this, as the first thing on the main page actually describes pretty good what diesel is:

> Diesel is a Safe, Extensible ORM and Query Builder for [Rust](https://www.rust-lang.org/)
>
> Diesel is the most productive way to interact with databases in Rust because of its safe and composable abstractions over queries.
