### ISSUE TITLE
Community projects

### ISSUE THREAD

**Issue by Wulf** [sgrif/diesel.rs-website#177]
Hey! Georg asked me to create a PR/issue for [dsync](https://github.com/Wulf/dsync) here.

I tried to find a place on the website where a list of community projects might go but all I can think of is another section on the guides page. Let me know, and I can create a PR!

**Comment by weiznich** [comment]
Another section on the guides page would be a solution or adding another section to the main page example selection [here](https://github.com/sgrif/diesel.rs-website/blob/2bc2bfa0be35fdc95e4888edf49beb87ac9cc73a/src/index.md?plain=1#L100). At least for a small list the main page seems like a better solution.

**Comment by Wulf** [comment]
I added a section on the main page, let me know if it looks okay. Otherwise, I can attempt to put something together on the guides page.

**Comment by weiznich** [comment]
Fixed by #180
