### ISSUE TITLE
Feature Request: impl<'a, Parent, Child> BelongingToDsl<(&'a [Parent], &'a [Parent])> for Child

### ISSUE THREAD

**Issue by Bajix** [sgrif/diesel.rs-website#193]
I authored [stack-queue](https://crates.io/crates/stack-queue) specifically so that I could create a data loader that integrates with Diesel. The current design only batches contiguous slices and simply starts a new batch whenever a task batch would otherwise wrap around to the beginning, however I could make this support wrap-around batching by returning an ordered pair of slices instead. The only way I could make this work and still integrate with BelongingToDsl without creating an intermediary Vec would be for BelongingToDsl to impl<'a, Parent, Child> BelongingToDsl<(&'a [Parent], &'a [Parent])> for Child

**Comment by weiznich** [comment]
This is the repository of the diesel webside, not the main diesel repository. Please move feature requests for diesel [here](https://github.com/diesel-rs/diesel/discussions/categories/ideas)
