### ISSUE TITLE
The Getting Started Guide should have an example for getting single item

### ISSUE THREAD

**Issue by ernest-rudnicki** [sgrif/diesel.rs-website#201]
Hey there!

I am learning Rust and I am trying to create my own api based on `actix-web` and `diesel-orm`. I was going through `Getting started` guide and while it had great examples for CRUD, it's missing an implementation for getting a single item from the database. I managed to find out how to do that in the end but it took me a while.

**Comment by weiznich** [comment]
I happily accept a PR for that if it does not extend the getting started guide that much (and also updates the relevant code example in the diesel repo)

**Comment by ernest-rudnicki** [comment]
That's great!, I will work on this then. I will try to make it as compact as possible 😄

**Comment by Tristan1435** [comment]
Hello, Just running thru the "Getting Started" guide.  I could not get get_post.rs to compile without "use diesel_demo::*;

currently opens with:
use self::models::Post;
use diesel::prelude::*;
use std::env::args;

needed to add:
use self::models::Post;
use diesel::prelude::*;
use diesel_demo::*;     // needs this line as per other examples?
use std::env::args;

Thank you.

**Comment by ernest-rudnicki** [comment]
@Tristan1435 Thanks! Looks like I have missed that, because each example had an import for their per their database. I removed that from the example that I added in `Getting Started` guide, but I haven't realized other examples are using `use diesel_demo::*` import. I prepared a Pull Request with a fix

https://github.com/sgrif/diesel.rs-website/pull/203

**Comment by weiznich** [comment]
Fixed by #203
