### ISSUE TITLE
Mention table! and diesel print-schema in the guide

### ISSUE THREAD

**Issue by killercup** [sgrif/diesel.rs-website#27]
It seems that many people are afraid of automatic schema inference. While we shouldn't change the guide to not use `infer_schema!`, we should probably mention in an info block that people can also use the `table!` macro and `diesel print-schema` on the CLI.

**Comment by sgrif** [comment]
> shouldn't s´change

Can't tell if unicode or typo

**Comment by killercup** [comment]
> Can't tell if unicode or typo

Just a typo. Thi̸ś ͠time̢!̡

**Comment by killercup** [comment]
Fixed in #39
