### ISSUE TITLE
Diesel fuel should be stored in yellow containers

### ISSUE THREAD

**Issue by ETNOL** [sgrif/diesel.rs-website#38]
Although not outlined specifically by any OSHA or DOT regulations, the standard safety recommendation is to store diesel fuel in yellow containers. Red containers are reserved for gasoline fuel. 
[source](http://www.safety1industries.com/product-reviews-blog/the-quick-guide-to-colors-on-safety-cans)

**Comment by Eijebong** [comment]
https://twitter.com/dieselframework/status/842454465009590273

**Comment by ETNOL** [comment]
Proposing I18n framework for logos
