### ISSUE TITLE
Batch insert example in the "All about inserts" guide renders incorrectly

### ISSUE THREAD

**Issue by jbcden** [sgrif/diesel.rs-website#49]
<img width="700" alt="screen shot 2017-12-24 at 12 12 14 pm" src="https://user-images.githubusercontent.com/1873996/34328118-b5cbb396-e8a3-11e7-9109-3163ac3f1824.png">

The main issue is the line:

```rust
let user_form = serde_json::from_str::>(json)?;
```

which should actually be:

```rust
let user_form = serde_json::from_str::<Vec<UserForm>>(json)?;
```
As per [this](https://github.com/diesel-rs/diesel/blob/v1.0.0-rc1/examples/postgres/all_about_inserts/src/lib.rs#L238). Not sure if this falls under the umbrella of https://github.com/sgrif/diesel.rs-website/issues/47 but wanted to note it here. I'm not too familiar with slim and I don't see anything obviously wrong with https://github.com/sgrif/diesel.rs-website/blob/master/source/views/guides/all-about-inserts.html.slim#L417 but perhaps I'm missing something obvious.

Looking at the rendered html it looks like `<Vec<UserForm>` portion of the type is being rendered as html:

<img width="459" alt="screen shot 2017-12-24 at 12 20 24 pm" src="https://user-images.githubusercontent.com/1873996/34328156-db94f2a8-e8a4-11e7-983f-a22a59176079.png">

**Comment by sgrif** [comment]
Ugh literally every time I publish a guide I forget that `<pre><code>` doesn't escape HTML tags >_>

**Comment by sgrif** [comment]
Should be fixed now. Let me know if I missed any.
