### ISSUE TITLE
QueryBuilder should be QueryFragment?

### ISSUE THREAD

**Issue by jbcden** [sgrif/diesel.rs-website#55]
![image](https://user-images.githubusercontent.com/1873996/34567148-166e81f4-f12f-11e7-809f-7b5d3f2534db.png)

Looking at the image above I noticed that the examples are all talking about implementing the `QueryFragment` trait but the text after mentions `QueryBuilder` which is not mentioned anywhere else in the guide. Should `QueryBuilder` actually be `QueryFragment`?

**Comment by sgrif** [comment]
Thanks! <3
