### ISSUE TITLE
Enable SSL

### ISSUE THREAD

**Issue by amilajack** [sgrif/diesel.rs-website#78]
Chrome now shows the URL as `not secure`. This can be done with a click of a button. In github pages config

**Comment by sgrif** [comment]
SSL is enabled on the site, it's just not enforced. Given that we do not serve any sensitive data on diesel.rs, I don't see any reason to enforce HTTPS -- you can always visit https://diesel.rs if you prefer to use SSL

**Comment by UnlimitedCookies** [comment]
Please forward all requests to https://. All websites should be encrypted, even non-sensitive websites to ensure integrity.

Refer: https://web.dev/why-https-matters/

**Comment by weiznich** [comment]
At least I cannot do much here, as I do not have the corresponding access right.
