### ISSUE TITLE
Broken link in Getting Started Guide

### ISSUE THREAD

**Issue by lukehsiao** [sgrif/diesel.rs-website#82]
The link to `dotenv` in the Getting Started Guide:

https://github.com/sgrif/diesel.rs-website/blob/2601d76e96a14e0db34428397b2ff0f2fe8c8005/source/views/guides/getting-started.html.slim#L46

Returns a 404.

The [`dotenv` docs](https://docs.rs/dotenv/0.13.0/dotenv/) might be a better place to point. 

Note that the `dotenv` docs point to https://github.com/purpliminal/rust-dotenv/, which is currently intentionally empty (https://github.com/purpliminal/rust-dotenv/issues/1), so pointing to the docs.rs may be a good solution until a GitHub repo is finalized.

**Comment by JohnTitor** [comment]
For now, https://github.com/dotenv-rs/dotenv seems a good place to point.
