### ISSUE TITLE
The tabs to switch between examples are hidden on mobile. The results are really confusing

### ISSUE THREAD

**Issue by sgrif** [sgrif/diesel.rs-website#9]
Not sure if the solution to this is to show them on mobile, or just to have the examples non-tabbed on mobile. /cc @corwinharrell take a look at the bottom of the page on mobile.

**Comment by corwinharrell** [comment]
@sgrif until I handed the site off, the tabs worked on mobile (They defaulted to a vertical accordion solution on smaller screen sizes. I can confirm that this was working.) which means that when the markup was edited or altered during the addition of new examples, the behavior was broken at some point. I will take a look when I get a chance and see if I can figure out what was changed. In the meantime, the vertical tab pattern was taken from thoughtbot's [refills](http://thoughtbot.github.io/refills/) under **patterns**, so feel free to take a look at that and see if you can identify what you changed.

**Comment by sgrif** [comment]
Awesome, I'll bisect it and figure out when it broke. Thanks!

**Comment by sgrif** [comment]
Turns out I had straight up deleted them because I didn't know what they were. XD

**Comment by corwinharrell** [comment]
Nice! haha
